# Generated by Django 4.1.6 on 2023-02-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0002_signup_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
