# Generated by Django 4.1.6 on 2023-02-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0005_remove_movies_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='up',
        ),
    ]
