# Generated by Django 4.1.6 on 2023-02-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0006_remove_movies_cast_remove_movies_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='default.png', upload_to='pics'),
        ),
    ]
