# Generated by Django 4.1.6 on 2023-02-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0008_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='Movie_name',
            new_name='movie_name',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='Selected_seats',
            new_name='selected_seats',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='U_name',
            new_name='u_name',
        ),
    ]
