# Generated by Django 4.1.6 on 2023-02-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0008_alter_movies_image'),
        ('ticketBooking', '0009_rename_movie_name_bookings_movie_name_and_more'),
    ]

    operations = [
    ]
