# Generated by Django 4.1.6 on 2023-02-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0012_remove_seats_id_seats_s_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='s_no',
        ),
        migrations.AddField(
            model_name='seats',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
