# Generated by Django 4.1.6 on 2023-02-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0013_remove_seats_s_no_seats_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='S_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
