# Generated by Django 4.1.6 on 2023-02-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0015_rename_s_no_seats_s_no1_rename_status_seats_status1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='prize',
            new_name='price',
        ),
    ]
