# Generated by Django 4.1.6 on 2023-02-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0011_delete_bookings'),
        ('ticketBooking', '0016_rename_prize_bookings_price'),
    ]

    operations = [
    ]
