# Generated by Django 4.1.6 on 2023-02-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0017_merge_20230211_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('selected_seats', models.CharField(max_length=100)),
                ('u_name', models.CharField(default='Nikitha', max_length=30)),
            ],
        ),
    ]
