# Generated by Django 4.1.6 on 2023-02-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0019_rename_show_time_shows_from_time_shows_m_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='u_name',
            field=models.CharField(max_length=30),
        ),
    ]
