# Generated by Django 4.1.6 on 2023-02-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0020_alter_bookings_u_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='From_time',
            field=models.ForeignKey(db_column='From_time', default='10:00:00', on_delete=django.db.models.deletion.CASCADE, to='ticketBooking.shows', to_field='From_time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shows',
            name='From_time',
            field=models.TimeField(unique=True),
        ),
    ]
