# Generated by Django 4.1.6 on 2023-02-12 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketBooking', '0021_seats_from_time_alter_shows_from_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Show_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 12, 15, 22, 48, 931933, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
